import { CityWeather } from '../types/weather';

export const mockCities: CityWeather[] = [
  {
    id: '1',
    city: 'Abu Dhabi',
    country: 'UAE',
    temperature: 32,
    condition: 'Sunny',
    high: 35,
    low: 28,
    localTime: '14:47',
    icon: 'sun',
    hourly: [
      { time: 'Now', temperature: 32, condition: 'Sunny', icon: 'sun' },
      { time: '15:00', temperature: 33, condition: 'Sunny', icon: 'sun' },
      { time: '16:00', temperature: 33, condition: 'Sunny', icon: 'sun' },
      { time: '17:00', temperature: 32, condition: 'Sunny', icon: 'sun' },
      { time: '18:00', temperature: 31, condition: 'Clear', icon: 'sun' },
      { time: '19:00', temperature: 30, condition: 'Clear', icon: 'moon' },
      { time: '20:00', temperature: 29, condition: 'Clear', icon: 'moon' },
      { time: '21:00', temperature: 28, condition: 'Clear', icon: 'moon' },
      { time: '22:00', temperature: 28, condition: 'Clear', icon: 'moon' },
      { time: '23:00', temperature: 27, condition: 'Clear', icon: 'moon' },
      { time: '00:00', temperature: 27, condition: 'Clear', icon: 'moon' },
      { time: '01:00', temperature: 26, condition: 'Clear', icon: 'moon' },
      { time: '02:00', temperature: 26, condition: 'Clear', icon: 'moon' },
      { time: '03:00', temperature: 25, condition: 'Clear', icon: 'moon' },
    ],
    daily: [
      { day: 'Today', condition: 'Sunny', icon: 'sun', high: 35, low: 28 },
      { day: 'Fri', condition: 'Sunny', icon: 'sun', high: 36, low: 29 },
      { day: 'Sat', condition: 'Partly Cloudy', icon: 'cloud-sun', high: 34, low: 27 },
      { day: 'Sun', condition: 'Cloudy', icon: 'cloud', high: 33, low: 26 },
      { day: 'Mon', condition: 'Sunny', icon: 'sun', high: 35, low: 28 },
      { day: 'Tue', condition: 'Sunny', icon: 'sun', high: 36, low: 29 },
      { day: 'Wed', condition: 'Partly Cloudy', icon: 'cloud-sun', high: 34, low: 27 },
      { day: 'Thu', condition: 'Sunny', icon: 'sun', high: 35, low: 28 },
      { day: 'Fri', condition: 'Sunny', icon: 'sun', high: 36, low: 29 },
      { day: 'Sat', condition: 'Sunny', icon: 'sun', high: 35, low: 28 },
    ],
    uvIndex: 9,
    uvLabel: 'Very High',
    windSpeed: 12,
    windDirection: 'NNE',
    windDegree: 25,
    humidity: 45,
    dewPoint: 18,
    aqi: 62,
    aqiLabel: 'Moderate',
    sunrise: '6:24 AM',
    sunset: '6:47 PM',
    precipitation: 0,
    precipitationForecast: 'No rain expected',
  },
  {
    id: '2',
    city: 'Dubai',
    country: 'UAE',
    temperature: 30,
    condition: 'Partly Cloudy',
    high: 33,
    low: 26,
    localTime: '14:47',
    icon: 'cloud-sun',
    hourly: [
      { time: 'Now', temperature: 30, condition: 'Partly Cloudy', icon: 'cloud-sun' },
      { time: '15:00', temperature: 31, condition: 'Partly Cloudy', icon: 'cloud-sun' },
      { time: '16:00', temperature: 32, condition: 'Sunny', icon: 'sun' },
      { time: '17:00', temperature: 31, condition: 'Sunny', icon: 'sun' },
      { time: '18:00', temperature: 30, condition: 'Clear', icon: 'sun' },
      { time: '19:00', temperature: 28, condition: 'Clear', icon: 'moon' },
      { time: '20:00', temperature: 27, condition: 'Clear', icon: 'moon' },
      { time: '21:00', temperature: 26, condition: 'Clear', icon: 'moon' },
      { time: '22:00', temperature: 26, condition: 'Clear', icon: 'moon' },
      { time: '23:00', temperature: 25, condition: 'Clear', icon: 'moon' },
      { time: '00:00', temperature: 25, condition: 'Clear', icon: 'moon' },
      { time: '01:00', temperature: 24, condition: 'Clear', icon: 'moon' },
      { time: '02:00', temperature: 24, condition: 'Clear', icon: 'moon' },
      { time: '03:00', temperature: 23, condition: 'Clear', icon: 'moon' },
    ],
    daily: [
      { day: 'Today', condition: 'Partly Cloudy', icon: 'cloud-sun', high: 33, low: 26 },
      { day: 'Fri', condition: 'Sunny', icon: 'sun', high: 34, low: 27 },
      { day: 'Sat', condition: 'Sunny', icon: 'sun', high: 33, low: 26 },
      { day: 'Sun', condition: 'Partly Cloudy', icon: 'cloud-sun', high: 32, low: 25 },
      { day: 'Mon', condition: 'Sunny', icon: 'sun', high: 34, low: 27 },
      { day: 'Tue', condition: 'Sunny', icon: 'sun', high: 35, low: 28 },
      { day: 'Wed', condition: 'Partly Cloudy', icon: 'cloud-sun', high: 33, low: 26 },
      { day: 'Thu', condition: 'Sunny', icon: 'sun', high: 34, low: 27 },
      { day: 'Fri', condition: 'Sunny', icon: 'sun', high: 35, low: 28 },
      { day: 'Sat', condition: 'Partly Cloudy', icon: 'cloud-sun', high: 33, low: 26 },
    ],
    uvIndex: 8,
    uvLabel: 'Very High',
    windSpeed: 16,
    windDirection: 'NE',
    windDegree: 45,
    humidity: 52,
    dewPoint: 19,
    aqi: 58,
    aqiLabel: 'Moderate',
    sunrise: '6:26 AM',
    sunset: '6:45 PM',
    precipitation: 0,
    precipitationForecast: 'No rain expected',
  },
  {
    id: '3',
    city: 'Kottayam',
    country: 'Kerala, India',
    temperature: 28,
    condition: 'Rainy',
    high: 30,
    low: 24,
    localTime: '16:17',
    icon: 'cloud-rain',
    hourly: [
      { time: 'Now', temperature: 28, condition: 'Rainy', icon: 'cloud-rain' },
      { time: '17:00', temperature: 27, condition: 'Rainy', icon: 'cloud-rain' },
      { time: '18:00', temperature: 27, condition: 'Cloudy', icon: 'cloud' },
      { time: '19:00', temperature: 26, condition: 'Cloudy', icon: 'cloud' },
      { time: '20:00', temperature: 26, condition: 'Cloudy', icon: 'cloud' },
      { time: '21:00', temperature: 25, condition: 'Cloudy', icon: 'cloud' },
      { time: '22:00', temperature: 25, condition: 'Cloudy', icon: 'cloud' },
      { time: '23:00', temperature: 24, condition: 'Cloudy', icon: 'cloud' },
      { time: '00:00', temperature: 24, condition: 'Cloudy', icon: 'cloud' },
      { time: '01:00', temperature: 24, condition: 'Cloudy', icon: 'cloud' },
      { time: '02:00', temperature: 23, condition: 'Cloudy', icon: 'cloud' },
      { time: '03:00', temperature: 23, condition: 'Cloudy', icon: 'cloud' },
      { time: '04:00', temperature: 23, condition: 'Cloudy', icon: 'cloud' },
      { time: '05:00', temperature: 22, condition: 'Cloudy', icon: 'cloud' },
    ],
    daily: [
      { day: 'Today', condition: 'Rainy', icon: 'cloud-sun', high: 11, low: 3 },
      { day: 'Fri', condition: 'Rainy', icon: 'cloud-rain', high: 10, low: 5, precipitation: 70 },
      { day: 'Sat', condition: 'Partly Cloudy', icon: 'sun', high: 11, low: 3 },
      { day: 'Sun', condition: 'Rainy', icon: 'cloud', high: 13, low: 5, precipitation: 70 },
      { day: 'Mon', condition: 'Rainy', icon: 'cloud-sun', high: 12, low: 5 },
      { day: 'Tue', condition: 'Cloudy', icon: 'cloud-sun', high: 9, low: 2 },
      { day: 'Wed', condition: 'Rainy', icon: 'cloud', high: 14, low: 5, precipitation: 40 },
      { day: 'Thu', condition: 'Partly Cloudy', icon: 'wind', high: 12, low: 1 },
      { day: 'Fri', condition: 'Rainy', icon: 'cloud-sun', high: 8, low: -1 },
      { day: 'Sat', condition: 'Rainy', icon: 'cloud', high: 12, low: 4 },
    ],
    uvIndex: 3,
    uvLabel: 'Moderate',
    windSpeed: 8,
    windDirection: 'SW',
    windDegree: 225,
    humidity: 82,
    dewPoint: 25,
    aqi: 35,
    aqiLabel: 'Good',
    sunrise: '6:12 AM',
    sunset: '6:05 PM',
    precipitation: 12.4,
    precipitationForecast: 'Heavy rain expected',
  },
  {
    id: '4',
    city: 'Kanjirappally',
    country: 'Kerala, India',
    temperature: 27,
    condition: 'Cloudy',
    high: 29,
    low: 23,
    localTime: '16:17',
    icon: 'cloud',
    hourly: [
      { time: 'Now', temperature: 27, condition: 'Cloudy', icon: 'cloud' },
      { time: '17:00', temperature: 27, condition: 'Cloudy', icon: 'cloud' },
      { time: '18:00', temperature: 26, condition: 'Cloudy', icon: 'cloud' },
      { time: '19:00', temperature: 25, condition: 'Cloudy', icon: 'cloud' },
      { time: '20:00', temperature: 25, condition: 'Cloudy', icon: 'cloud' },
      { time: '21:00', temperature: 24, condition: 'Cloudy', icon: 'cloud' },
      { time: '22:00', temperature: 24, condition: 'Cloudy', icon: 'cloud' },
      { time: '23:00', temperature: 23, condition: 'Cloudy', icon: 'cloud' },
      { time: '00:00', temperature: 23, condition: 'Cloudy', icon: 'cloud' },
      { time: '01:00', temperature: 23, condition: 'Cloudy', icon: 'cloud' },
      { time: '02:00', temperature: 22, condition: 'Cloudy', icon: 'cloud' },
      { time: '03:00', temperature: 22, condition: 'Cloudy', icon: 'cloud' },
      { time: '04:00', temperature: 22, condition: 'Cloudy', icon: 'cloud' },
      { time: '05:00', temperature: 21, condition: 'Cloudy', icon: 'cloud' },
    ],
    daily: [
      { day: 'Today', condition: 'Cloudy', icon: 'cloud', high: 29, low: 23 },
      { day: 'Fri', condition: 'Rainy', icon: 'cloud-rain', high: 28, low: 23 },
      { day: 'Sat', condition: 'Partly Cloudy', icon: 'cloud-sun', high: 30, low: 24 },
      { day: 'Sun', condition: 'Rainy', icon: 'cloud-rain', high: 27, low: 22 },
      { day: 'Mon', condition: 'Cloudy', icon: 'cloud', high: 29, low: 23 },
      { day: 'Tue', condition: 'Partly Cloudy', icon: 'cloud-sun', high: 30, low: 24 },
      { day: 'Wed', condition: 'Rainy', icon: 'cloud-rain', high: 27, low: 22 },
      { day: 'Thu', condition: 'Cloudy', icon: 'cloud', high: 29, low: 23 },
      { day: 'Fri', condition: 'Rainy', icon: 'cloud-rain', high: 28, low: 23 },
      { day: 'Sat', condition: 'Partly Cloudy', icon: 'cloud-sun', high: 30, low: 24 },
    ],
    uvIndex: 4,
    uvLabel: 'Moderate',
    windSpeed: 6,
    windDirection: 'S',
    windDegree: 180,
    humidity: 75,
    dewPoint: 22,
    aqi: 28,
    aqiLabel: 'Good',
    sunrise: '6:13 AM',
    sunset: '6:04 PM',
    precipitation: 5.2,
    precipitationForecast: 'Light rain possible',
  },
  {
    id: '5',
    city: 'Alappuzha',
    country: 'Kerala, India',
    temperature: 29,
    condition: 'Partly Cloudy',
    high: 31,
    low: 25,
    localTime: '16:17',
    icon: 'cloud-sun',
    hourly: [
      { time: 'Now', temperature: 29, condition: 'Partly Cloudy', icon: 'cloud-sun' },
      { time: '17:00', temperature: 29, condition: 'Partly Cloudy', icon: 'cloud-sun' },
      { time: '18:00', temperature: 28, condition: 'Partly Cloudy', icon: 'cloud-sun' },
      { time: '19:00', temperature: 27, condition: 'Cloudy', icon: 'cloud' },
      { time: '20:00', temperature: 27, condition: 'Cloudy', icon: 'cloud' },
      { time: '21:00', temperature: 26, condition: 'Cloudy', icon: 'cloud' },
      { time: '22:00', temperature: 26, condition: 'Cloudy', icon: 'cloud' },
      { time: '23:00', temperature: 25, condition: 'Cloudy', icon: 'cloud' },
      { time: '00:00', temperature: 25, condition: 'Cloudy', icon: 'cloud' },
      { time: '01:00', temperature: 25, condition: 'Cloudy', icon: 'cloud' },
      { time: '02:00', temperature: 24, condition: 'Cloudy', icon: 'cloud' },
      { time: '03:00', temperature: 24, condition: 'Cloudy', icon: 'cloud' },
      { time: '04:00', temperature: 24, condition: 'Cloudy', icon: 'cloud' },
      { time: '05:00', temperature: 23, condition: 'Cloudy', icon: 'cloud' },
    ],
    daily: [
      { day: 'Today', condition: 'Partly Cloudy', icon: 'cloud-sun', high: 31, low: 25 },
      { day: 'Fri', condition: 'Rainy', icon: 'cloud-rain', high: 30, low: 24 },
      { day: 'Sat', condition: 'Partly Cloudy', icon: 'cloud-sun', high: 32, low: 25 },
      { day: 'Sun', condition: 'Rainy', icon: 'cloud-rain', high: 29, low: 24 },
      { day: 'Mon', condition: 'Partly Cloudy', icon: 'cloud-sun', high: 31, low: 25 },
      { day: 'Tue', condition: 'Sunny', icon: 'sun', high: 33, low: 26 },
      { day: 'Wed', condition: 'Rainy', icon: 'cloud-rain', high: 29, low: 24 },
      { day: 'Thu', condition: 'Partly Cloudy', icon: 'cloud-sun', high: 31, low: 25 },
      { day: 'Fri', condition: 'Rainy', icon: 'cloud-rain', high: 30, low: 24 },
      { day: 'Sat', condition: 'Partly Cloudy', icon: 'cloud-sun', high: 32, low: 25 },
    ],
    uvIndex: 6,
    uvLabel: 'High',
    windSpeed: 14,
    windDirection: 'W',
    windDegree: 270,
    humidity: 70,
    dewPoint: 23,
    aqi: 42,
    aqiLabel: 'Good',
    sunrise: '6:11 AM',
    sunset: '6:06 PM',
    precipitation: 3.8,
    precipitationForecast: 'Possible showers',
  },
  {
    id: '6',
    city: 'Scotland',
    country: 'UK',
    temperature: 8,
    condition: 'Rainy',
    high: 10,
    low: 4,
    localTime: '11:47',
    icon: 'cloud-rain',
    hourly: [
      { time: 'Now', temperature: 8, condition: 'Rainy', icon: 'cloud-rain' },
      { time: '12:00', temperature: 9, condition: 'Rainy', icon: 'cloud-rain' },
      { time: '13:00', temperature: 10, condition: 'Rainy', icon: 'cloud-rain' },
      { time: '14:00', temperature: 10, condition: 'Cloudy', icon: 'cloud' },
      { time: '15:00', temperature: 9, condition: 'Cloudy', icon: 'cloud' },
      { time: '16:00', temperature: 8, condition: 'Cloudy', icon: 'cloud' },
      { time: '17:00', temperature: 7, condition: 'Cloudy', icon: 'cloud' },
      { time: '18:00', temperature: 6, condition: 'Clear', icon: 'moon' },
      { time: '19:00', temperature: 6, condition: 'Clear', icon: 'moon' },
      { time: '20:00', temperature: 5, condition: 'Clear', icon: 'moon' },
      { time: '21:00', temperature: 5, condition: 'Clear', icon: 'moon' },
      { time: '22:00', temperature: 4, condition: 'Clear', icon: 'moon' },
      { time: '23:00', temperature: 4, condition: 'Clear', icon: 'moon' },
      { time: '00:00', temperature: 4, condition: 'Clear', icon: 'moon' },
    ],
    daily: [
      { day: 'Today', condition: 'Rainy', icon: 'cloud-rain', high: 10, low: 4 },
      { day: 'Fri', condition: 'Rainy', icon: 'cloud-rain', high: 9, low: 3 },
      { day: 'Sat', condition: 'Partly Cloudy', icon: 'cloud-sun', high: 11, low: 5 },
      { day: 'Sun', condition: 'Cloudy', icon: 'cloud', high: 10, low: 4 },
      { day: 'Mon', condition: 'Rainy', icon: 'cloud-rain', high: 9, low: 3 },
      { day: 'Tue', condition: 'Partly Cloudy', icon: 'cloud-sun', high: 12, low: 6 },
      { day: 'Wed', condition: 'Rainy', icon: 'cloud-rain', high: 8, low: 2 },
      { day: 'Thu', condition: 'Cloudy', icon: 'cloud', high: 10, low: 4 },
      { day: 'Fri', condition: 'Rainy', icon: 'cloud-rain', high: 9, low: 3 },
      { day: 'Sat', condition: 'Partly Cloudy', icon: 'cloud-sun', high: 11, low: 5 },
    ],
    uvIndex: 1,
    uvLabel: 'Low',
    windSpeed: 22,
    windDirection: 'NW',
    windDegree: 315,
    humidity: 88,
    dewPoint: 6,
    aqi: 18,
    aqiLabel: 'Good',
    sunrise: '7:52 AM',
    sunset: '4:23 PM',
    precipitation: 8.6,
    precipitationForecast: 'Rain expected throughout the day',
  },
];